// ── Talent Arena constants ──
export const STAGE_COLORS = {"XPRO stage": "#FFD700", "XPRO Lab": "#FF6B35", "XPRO Talks": "#00BCD4", "Visionary Stage": "#9B59B6", "Hotspot Talks": "#3498DB", "Plug-in Talks": "#E74C3C", "Focus Lab": "#2ECC71", "Frontier lab": "#FF4081", "Meetup area": "#78909C", "Barcelona": "#FFEB3B", "Skills Hub": "#26A69A", "Robotics": "#7C4DFF", "Gaming": "#F50057"};
export const STAGE_ORDER = ["XPRO stage", "XPRO Lab", "XPRO Talks", "Visionary Stage", "Hotspot Talks", "Plug-in Talks", "Focus Lab", "Frontier lab", "Meetup area", "Barcelona", "Skills Hub", "Robotics", "Gaming"];
export const ALL_TAGS = ["Artificial Intelligence", "Cloud Computing", "Cybersecurity", "Future Trends", "GAMING", "Management", "ROBOTICS", "Software Development"];
export const LANG_FLAGS = {English: "\u{1F1EC}\u{1F1E7}", Spanish: "\u{1F1EA}\u{1F1F8}", Catalan: "\u{1F3F4}"};
export const LANG_CLASS = {English: "lang-en", Spanish: "lang-es", Catalan: "lang-ca"};
export const ALL_LANGS = ["English", "Spanish", "Catalan"];

// ── MWC Barcelona constants ──
export const MWC_STAGE_COLORS = {"4YFN Meeting Hub":"#dc3b3b","4YFN Networking Hub":"#dc573b","4YFN Pitching Stage":"#dc733b","4YFN Workshop Room":"#dc8e3b","Agora Stage":"#dcaa3b","Banco Sabadell Stage":"#dcc53b","CC2 GSMA Insights Hub Stage":"#d7dc3b","CC2.1 MWC Roundtable Room 1":"#bcdc3b","CC2.2 MWC Roundtable Room 2":"#a0dc3b","CC2.3 GSMA Insights Hub":"#85dc3b","CC2.5 GSMA Insights Hub":"#69dc3b","CC5 Focus Stage":"#4edc3b","CC5 Ministerial Stage":"#3bdc45","Connected Industries":"#3bdc60","Ericsson pavilion":"#3bdc7c","Founders Stage":"#3bdc97","GSMA Summits Stage":"#3bdcb3","Johnson Stage":"#3bdcce","Lamarr Stage":"#3bcedc","Leaders Lounge":"#3bb3dc","MWC Broadcast Stage":"#3b97dc","MWC Main Stage":"#3b7cdc","MWC Networking Hub":"#3b60dc","Marconi Stage":"#3b45dc","New Frontiers Stage":"#4e3bdc","Partner Theatre 1":"#693bdc","Partner Theatre 2":"#853bdc","Partner Theatre 3":"#a03bdc","Partner Theatre 4":"#bc3bdc","Partner Theatre 5":"#d73bdc","Partner Theatre 6":"#dc3bc5","PwC - Stand 4D10":"#dc3baa","Sky Stage":"#dc3b8e","Tech Mahindra - Stand 2D46":"#dc3b73","Turing Stage":"#dc3b57"};
export const MWC_STAGE_ORDER = ["MWC Main Stage","MWC Broadcast Stage","MWC Networking Hub","GSMA Summits Stage","Agora Stage","Marconi Stage","Johnson Stage","Lamarr Stage","Turing Stage","New Frontiers Stage","Founders Stage","Leaders Lounge","Connected Industries","CC5 Focus Stage","CC5 Ministerial Stage","CC2 GSMA Insights Hub Stage","CC2.1 MWC Roundtable Room 1","CC2.2 MWC Roundtable Room 2","CC2.3 GSMA Insights Hub","CC2.5 GSMA Insights Hub","Banco Sabadell Stage","Sky Stage","4YFN Pitching Stage","4YFN Meeting Hub","4YFN Networking Hub","4YFN Workshop Room","Partner Theatre 1","Partner Theatre 2","Partner Theatre 3","Partner Theatre 4","Partner Theatre 5","Partner Theatre 6","Ericsson pavilion","PwC - Stand 4D10","Tech Mahindra - Stand 2D46"];
export const ALL_MWC_THEMES = ["AI NEXUS","AI4ENTERPRISE","CLIMATE TECH","CONNECT AI","CORPORATE INNOVATION","CREATIVITY","CYBERSECURITY","FINTECH","FOUNDERS ACADEMY","GAME CHANGERS","GAMING","HEALTH TECH","INFINITE AI","INTELLIGENT INFRASTRUCTURE","INVESTORS","TECH4ALL","UNIVERSITIES & SPIN-OFFS"];
export const ALL_MWC_ACCESS = ["Open to All","Pass Required to Access","Invitation Required","Pre-registered & Approved have priority"];
export const ALL_MWC_INTERESTS = ["5G / 6G","AI NEXUS","AI4ENTERPRISE","APP / MOBILE SERVICES","ARTIFICIAL INTELLIGENCE","AUTOMOTIVE / TRANSPORT","BIG DATA / ANALYTICS","BLOCKCHAIN / DECENTRALISATION","CLIMATE / ENVIRONMENT / SUSTAINABILITY","CLIMATE TECH","CLOUD SERVICES / DATACENTERS","CONNECT AI","CORPORATE INNOVATION","CORPORATE VENTURING","CREATIVITY","CYBERSECURITY","DIGITAL IDENTITY / AUTHENTICATION","DIGITAL MARKETING / ADTECH","DIVERSITY","E-COMMERCE","EDUCATION","ENTERPRISE SOLUTIONS","ENTREPRENEURSHIP","FINTECH","FINTECH / FINANCE / INSURANCE SERVICES","FOUNDERS","FOUNDERS ACADEMY","GAME CHANGERS","GAMING","GOVERNMENT / PUBLIC POLICY","HEALTH / FITNESS / WELLBEING","HEALTH TECH","IMPACT / SOCIAL INNOVATION","INFINITE AI","INNOVATION ECOSYSTEMS","INTELLIGENT INFRASTRUCTURE","INVESTORS","IOT","MANUFACTURING AND INDUSTRY 4.0","MEDIA / CONTENT / ENTERTAINMENT","MOBILE DEVICE HARDWARE","MOBILE DEVICE SOFTWARE","NETWORK INFRASTRUCTURE","NETWORK SECURITY","PRIVATE NETWORKS","QUANTUM","RETAIL / DISTRIBUTION CHANNELS","SATELLITE / NON TERRESTRIAL NETWORKS","SMART CITIES","SYSTEMS INTEGRATION","TALENT","TECH4ALL","TOWER & FIBRE","UNIVERSITIES & SPIN-OFFS","VENTURE CAPITAL / INVESTMENT / M&A","VIRTUAL REALITY / AUGMENTED REALITY"];
